# ----------------------------------------------------------------------------------------
#  HEIG-VD ///////////////////////////////////////////////////////////////////////////////
#  Haute Ecole d'Ingenerie et de Gestion du Canton de Vaud
#  School of Business and Engineering in Canton de Vaud
# ----------------------------------------------------------------------------------------
#  REDS Institute ////////////////////////////////////////////////////////////////////////
#  Reconfigurable Embedded Digital Systems
# ----------------------------------------------------------------------------------------
#
#  File                 : maxv_top.sdc
#  Author               : Bruno Sutterlet
#  Date                 : 28.05.2013
#  Target Devices       : Altera MAXV 5M570ZF256C5
#
#  Context              : Max_V_Board Project : Hardware bring-up
#
# ----------------------------------------------------------------------------------------
#  Description :
#    Clock deffinition
# ----------------------------------------------------------------------------------------
#  Information :
#    30.09.2014  EMI  Adaptation for the aff_min_max lab
#
# ----------------------------------------------------------------------------------------
#  Modifications :
#  Ver   Date        Engineer     Changes
#  1.0   ???         ???          Generated by Quartus 18.0
#  1.1   18.05.26    BST          Added CLK_Gen_i
#
# ----------------------------------------------------------------------------------------

# Clock constraints

create_clock -name "Clk_Main_i" -period 1000.000ns [get_ports {Clk_Main_i}]

create_clock -name "Clk_Gen_i" -period 25.000ns [get_ports {Clk_Gen_i}]

# tsu/th constraints

# tco constraints

# tpd constraints

